main: tfmc.justin.geiger_counter
version: 1.1.1
name: geiger_counter
author: Justin
api-version: 1.21
depend: [TLibs]
commands:
  geiger:
    description: Geiger Counter admin commands
    usage: /geiger <locate|move [x z]|reload>
    permission: geiger.admin
permissions:
  geiger.admin:
    description: Access to Geiger Counter admin commands
    default: op
